type: lamp
php: 8.4
database: mariadb:11.4

# The sample database can be obtained at:
# https://probosupportfiles.blob.core.windows.net/utils/joomla.sql.gz
assets:
  - joomla.sql.gz

steps:
  - name: Setup Joomla
    plugin: Joomla
    database: joomla.sql.gz
    databaseGzipped: true
    clearCaches: false
    subDirectory: docroot
    databasePrefix: fjoms_
    dbType: mysql
    clearCaches: true

  - name: Set Joomla Cache File Permissions
    plugin: Script
    script:
      - chmod -R 777 /var/www/html/administrator
      - chmod -R 777 /var/www/html/tmp
